# Generated by Django 3.2.5 on 2021-10-14 17:39

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('CardId', models.CharField(blank=True, max_length=20)),
                ('YearofBirth', models.IntegerField(blank=True)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('school', models.CharField(max_length=256)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('times_of_scan', models.IntegerField(default=0, editable=False)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
