# Generated by Django 3.2.5 on 2021-10-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='YearofBirth',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
